// Provider and environment configuration for application infrastructure.
terraform {
  required_version = ">= 1.10.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.100"
    }
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Project     = "realworld-devops"
      Environment = var.environment
      ManagedBy   = "Terraform"
    }
  }
}

variable "aws_region" {
  description = "AWS region for this environment."
  type        = string
  default     = "ap-south-1"
}

variable "environment" {
  description = "Environment name used in resource names and tags."
  type        = string
  default     = "dev"
}

variable "db_instance_class" {
  description = "RDS instance class. The selected class must be available in the configured region."
  type        = string
  default     = "db.t4g.micro"
}

variable "db_storage_gib" {
  description = "Initial encrypted RDS storage size in GiB."
  type        = number
  default     = 20

  validation {
    condition     = var.db_storage_gib >= 20
    error_message = "RDS PostgreSQL requires at least 20 GiB of allocated storage."
  }
}

variable "lambda_package_path" {
  description = "Path to the prebuilt Lambda deployment ZIP, generated by Jenkins."
  type        = string
  default     = "lambda.zip"
}

variable "lambda_package_key" {
  description = "Key of the immutable Lambda package uploaded to the private artifact bucket."
  type        = string
  default     = "lambda/latest.zip"
}

variable "jenkins" {
  description = "Existing Jenkins EC2 network and IAM role details. Leave null until configured."
  type = object({
    vpc_id            = string
    vpc_cidr          = string
    route_table_id    = string
    security_group_id = string
    iam_role_name     = string
  })
  default  = null
  nullable = true

  validation {
    condition     = var.jenkins == null ? true : can(cidrnetmask(var.jenkins.vpc_cidr))
    error_message = "jenkins.vpc_cidr must be a valid IPv4 CIDR block."
  }
}

locals {
  name                    = "realworld-${var.environment}"
  jenkins_peering_enabled = var.jenkins != null
}
